### ISSUE TITLE
The environment name changed in assignment4

### ISSUE THREAD

**Issue by dayekuaipao** [cuhkrlcourse/ierg6130-assignment#11]
The enviroment name changed to cPong from CompetitivePong.

**Comment by pengzhenghao** [comment]
I switch the name automatically to cPong-v0 if you input CompetitivePong-v0 in make_envs. This should make the assignment working with the latest CompetitivePong.

https://github.com/cuhkrlcourse/competitive-pong/blob/1ae300bec13e507eb3f72a41a6b38a1b96672630/competitive_pong/make_envs.py#L53
