### ISSUE TITLE
how to use jupyter notebook?

### ISSUE THREAD

**Issue by yangqie** [cuhkrlcourse/ierg6130-assignment#9]
question one
" Install and use jupyter notebook
Now you have installed the jupyter notebook. Go to the directory FILE.ipynb located, command: "

Please give more details about the directory FILE.ipynb located.

question two
env = gym.make('CartPole-v0')
env.reset()
for _ in range(500):
    env.render()
    obs, reward, done, info = env.step(env.action_space.sample())
    if done:
        env.reset()  # press q to quit
env.close()
when i run this code in ipython, i get some error,How to deal with？

~/anaconda3/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    172 
    173         if self.viewer is None:
--> 174             from gym.envs.classic_control import rendering
    175             self.viewer = rendering.Viewer(screen_width, screen_height)
    176             l, r, t, b = -cartwidth / 2, cartwidth / 2, cartheight / 2, -cartheight / 2

~/anaconda3/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in <module>
     30     If you're running on a server, you may need a virtual frame buffer; something like this should work:
     31     'xvfb-run -s \"-screen 0 1400x900x24\" python <your_script.py>'
---> 32     ''')
     33 
     34 import math

ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'

**Comment by Barley-zhang** [comment]
about one:
FILE.ipynb is a creat new file by yourself .
激活环境：conda activate ierg6130
退出环境：conda deactivate
打开notebook：jupyter notebook
关闭notebook: ctrl+c



about two:
may be you can try 'apt-get install python-opengl'




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cuhkrlcourse/ierg6130-assignment"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 下午5:38
收件人:&nbsp;"cuhkrlcourse/ierg6130-assignment"<ierg6130-assignment@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cuhkrlcourse/ierg6130-assignment] how to use jupyter notebook? (#9)





 
question one
 " Install and use jupyter notebook
 Now you have installed the jupyter notebook. Go to the directory FILE.ipynb located, command: "
 
Please give more details about the directory FILE.ipynb located.
 
question two
 env = gym.make('CartPole-v0')
 env.reset()
 for _ in range(500):
 env.render()
 obs, reward, done, info = env.step(env.action_space.sample())
 if done:
 env.reset()  # press q to quit
 env.close()
 when i run this code in ipython, i get some error,How to deal with？
 
~/anaconda3/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
 172
 173         if self.viewer is None:
 --&gt; 174             from gym.envs.classic_control import rendering
 175             self.viewer = rendering.Viewer(screen_width, screen_height)
 176             l, r, t, b = -cartwidth / 2, cartwidth / 2, cartheight / 2, -cartheight / 2
 
~/anaconda3/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in 
 30     If you're running on a server, you may need a virtual frame buffer; something like this should work:
 31     'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py&gt;'
 ---&gt; 32     ''')
 33
 34 import math
 
ImportError:
 Error occurred while running from pyglet.gl import *
 HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
 If you're running on a server, you may need a virtual frame buffer; something like this should work:
 'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py&gt;'

**Comment by pengzhenghao** [comment]
> Please give more details about the directory FILE.ipynb located.

That means you should `cd assignment1` then start the notebook  `jupyter notebook`.

> question two

Try what @Barley-zhang suggests. Thanks Barley.

Please feel free to reopen this issue if you have any other question~
